### ISSUE TITLE
您好，模型权重文件已失效，可否重新上传一份。谢谢！

### ISSUE THREAD

**Issue by unnamex** [zyqhnu/Attention_O-Net#2]

**Comment by zyqhnu** [comment]
稍等，晚上上传。

**Comment by unnamex** [comment]
非常感谢！




944985538
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyqhnu/Attention_O-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyqhnu/Attention_O-Net] 您好，模型权重文件已失效，可否重新上传一份。谢谢！ (Issue #2)





 
稍等，晚上上传。

**Comment by zyqhnu** [comment]
已经很久没看过这个代码了，去翻找了很久，甚至仍不知道这个权重是不是当时上传的那版。
但您可以尝试一下
链接：https://pan.baidu.com/s/1hGN3e5iQgjsVYgn6kfPWNg?pwd=0225 
提取码：0225
另外，也很感谢您对我之前的工作感兴趣。

**Comment by unnamex** [comment]
拜读您的文章，十分受用！再次感谢您的分享，谢谢！
