### ISSUE TITLE
您好，关于代码中marker文件问题

### ISSUE THREAD

**Issue by L1849469801** [zyqhnu/Attention_O-Net#3]
您好，在代码中没有将数据集标签处理成marker文件的代码，请问marker文件是在其他地方生成的吗？

**Comment by zyqhnu** [comment]
您好，在io.py文件里有将关键点坐标(x, y)（对于眼底数据集请将添加全0的第三维，即z轴）坐标转换成marker 
[代码锚点](https://github.com/zyqhnu/Attention_O-Net/blob/ec95f70beae5b74bac9ba5074e7b0c6216e694f0/io1.py#L111C1-L111C15)

这么离谱的转换是为了和swc文件兼容，与Vaa3D兼容。（我也觉得很离谱，但是没办法。）
或许，过些天我抽出时间来可以写一个Torch版的。但愿有时间吧。

**Comment by L1849469801** [comment]
大佬您好，研一小白真诚发问，整个模型，首先要对数据集进行处理，研读几天代码，始终不得要领，请问想要运行整个模型，开启训练，要走那几步。是先运行local_max_all_range_allmodel_4_attn_chai.py这个脚本生成marker文件吗？但是在这个文件中没有看到加载原始图像的代码，直接加载的是.npy文件，请问这些npy文件是预先处理好的吗？对您的文章非常感兴趣，想跑通代码，希望您不吝赐教。

**Comment by zyqhnu** [comment]
您好，很高兴你感兴趣。
你能跑通推理/测试了嘛？如果可以推理，再去跑训练应该会更好、更熟悉。
第一个问题，是先对数据集进行处理，但local_max_all_range_allmodel_4_attn_chai.py是最后提取关键点的代码，网络运行后生成的是与输入图片等大的单通道图片，里面的值越大说明此处是关键点的概率越大，通过上述代码提取精确坐标。

下面这个是预处理，将坐标点、原图、分割图（groundtruth）转化为训练数据和标签（训练需要三种：原图、二值局部分割图、高斯热图，分别放在[这三个文件夹中](https://github.com/zyqhnu/Attention_O-Net/blob/ec95f70beae5b74bac9ba5074e7b0c6216e694f0/Heatmap_RALabel_Generation.py#L245C1-L247C30)）的脚本：1、[标签生成](https://github.com/zyqhnu/Attention_O-Net/blob/main/Heatmap_RALabel_Generation.py)))

**Comment by zyqhnu** [comment]
我的邮箱 yqzhang@hnu.edu.cn，也可以直接邮件交流。GitHub不一定能看到

**Comment by L1849469801** [comment]
十分感谢！
